### ISSUE TITLE
Add release workflow

### ISSUE THREAD

**Issue by Brainicism** [Brainicism/bgutil-ytdlp-pot-provider#2]

**Comment by grqz** [comment]
References:  
* https://github.com/coletdjnz/yt-dlp-get-pot/blob/master/.github/workflows/release.yml

**Comment by grqz** [comment]
refer to https://github.com/coletdjnz/yt-dlp-get-pot/blob/master/.github/workflows/release.yml
may need to change [Line48](https://github.com/coletdjnz/yt-dlp-get-pot/blob/3259757fe66317ecb0018fcda33a206c272b475e/.github/workflows/release.yml#L48) or add a `cd plugin` command, create a pyproject.toml

**Comment by grqz** [comment]
Note for self:pypi publishing: https://packaging.python.org/en/latest/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/
