### ISSUE TITLE
Fix readme and proxy question?

### ISSUE THREAD

**Issue by Elite** [Brainicism/bgutil-ytdlp-pot-provider#32]
A). This `cd bgutils-ytdlp-pot-provider/server/` should be `cd bgutil-ytdlp-pot-provider/server/` (extra s) in the instructions.
B). How to make the provider automatically use the IP/proxy used by the `yt-dlp` ?

**Comment by Brainicism** [comment]
A) Thanks for the call out, will fix that
B) Can you elaborate on your use-case for the proxy? Is this to bypass complete IP bans? If your IP is being flagged and being targeted with the "I am not a bot" prompt, passing PO token should already mitigate that most of the time.

**Comment by Elite** [comment]
@Brainicism During my tests using seproDev earlier development branch (https://discord.com/channels/807245652072857610/1272517645778026562), it seemed it will still get IP banned but after few thousand downloads. Since, I am using this on a public facing server the idea was to get potoken for every ip/proxy used.

**Comment by Brainicism** [comment]
> @Brainicism During my tests using seproDev earlier development branch (https://discord.com/channels/807245652072857610/1272517645778026562), it seemed it will still get IP banned but after few thousand downloads. Since, I am using this on a public facing server the idea was to get potoken for every ip/proxy used.

Got it. Will look into proxy support when we have time

**Comment by Brainicism** [comment]
@Elite Proxy support is out in 0.6.0

**Comment by Elite** [comment]
So this will use proxy passed to `yt-dlp`
