### ISSUE TITLE
Still getting asked to login after POT provided

### ISSUE THREAD

**Issue by RnJ4** [Brainicism/bgutil-ytdlp-pot-provider#37]
Hi, I was trying to run yt-dlp inside GitHub Actions container. The provider is running in docker, but the error persists.

> [youtube+GetPOT] Extracting URL: https://www.youtube.com/watch?v=GdtIKYTcdQw
[youtube+GetPOT] GdtIKYTcdQw: Downloading webpage
[youtube+GetPOT] GdtIKYTcdQw: Downloading ios player API JSON
[GetPOT] BgUtilHTTPPot: Generating POT via HTTP server
[youtube+GetPOT] GdtIKYTcdQw: Downloading web creator player API JSON
ERROR: [youtube+GetPOT] GdtIKYTcdQw: Sign in to confirm you’re not a bot. This helps protect our community. Learn more

The entire command generated by my script is 

> yt-dlp  -S quality,codec:avc:m4a "https://www.youtube.com/watch?v=GdtIKYTcdQw" --download-sections *00:29:30-00:32:30 -o temp/output0.mp4

Maybe there is something incompatible with those arguments?

Here is the link to the entire run https://github.com/RnJ4/YTClipper/actions/runs/10980263697/job/30485839298

**Comment by Brainicism** [comment]
As of some time yesterday, youtube appears to have flipped some feature flag on their end breaking this solution for most datacenter IP addresses. 

Related issues:
https://github.com/LuanRT/YouTube.js/issues/760
https://github.com/iv-org/invidious/issues/4734#issuecomment-2365205990
https://github.com/LuanRT/BgUtils/issues/7

**Comment by RnJ4** [comment]
Oh, that's quite unfortunate.😥 Thanks for sharing
