### ISSUE TITLE
Add a basic retry on fetch

### ISSUE THREAD

**Issue by coletdjnz** [Brainicism/bgutil-ytdlp-pot-provider#43]
https://github.com/Brainicism/bgutil-ytdlp-pot-provider/blob/9237eec6ecf8ba1fba7771a0bff99ab962b5f27d/server/src/session_manager.ts#L167-L193

Currently if there is a brief network issue or outage, these requests may fail causing an HTTP 500 to be received on yt-dlp end and no PO Token added to the request.

Perhaps a basic retry (with a limit) could be added to requests (e.g. retry 3 times before giving up)?

**Comment by Brainicism** [comment]
@coletdjnz 
Adding retries as part of #44  
Do you think your plugin framework should also attempt a retry if not PO token was received from the provider? Or at least throw a specific error so that the user knows what happened.

**Comment by coletdjnz** [comment]
> Do you think your plugin framework should also attempt a retry if not PO token was received from the provider?

I think this would be up to the provider plugin to implement, as it is dependent on the implementation whether it can be retried or not.

>  Or at least throw a specific error so that the user knows what happened.

It does raise a warning if a RequestError is thrown
