### ISSUE TITLE
Re-use session manager between requests?

### ISSUE THREAD

**Issue by bcomnes** [Brainicism/bgutil-ytdlp-pot-provider#5]
Did you intend for the session manager to be re-used between requests?

https://github.com/Brainicism/bgutil-ytdlp-pot-provider/blob/51afd7d693d9fb25a6b0d8cf553826eb0ee5b607/server/src/main.ts#L18

It's implemented to create a new manager for every request, but the session manager seems to try to keep around this.youtubeSessionData for re-use. 

Also apologies if I am just reading something wrong.

**Comment by Brainicism** [comment]
You are reading this correctly. Made this in a bit of a rush and forgot that I was re-creating the instance on every request while I was debugging something.

Feel free to put up a PR, otherwise I'll fix it some time later

**Comment by bcomnes** [comment]
Will PR anything useful back. Thanks for the helpful reference!
